In [1]:
import numpy as np
import pandas as pd
from datasets import Dataset
from datetime import datetime

In [2]:
import vectors

# Load dataset

In [3]:
# load dataframe
df = pd.read_csv('../data/data-kb.csv', sep='\t', dtype=str) # they are all strings!
df

,pmid,elocationid,title,journal,year,author,affiliation,abstract
0,40935315,doi: 10.1016/j.expneurol.2025.115457,Longitudinal analysis of age-dependent phenoty...,Experimental neurology,2025,"Aiswaria Lekshmi Kannan, Abhisarika Patnaik, A...","Neuroscience Division, IRCCS San Raffaele Scie...",Mutations in cyclin-dependent kinase-like 5 (C...
1,40935250,doi: 10.1016/j.jad.2025.120270,Adverse childhood experiences and cardiometabo...,Journal of affective disorders,2025,"Alyna Turner, Maya Kuperberg, Hugh McGovern, A...","Deakin University, School of Medicine, IMPACT,...",Bipolar disorder is associated with increased ...
2,40935239,pii: S0306-4522(25)00924-8,Endocrine circuitry in autism spectrum disorde...,Neuroscience,2025,"Maria Angelopoulou, Panayiotis Siaperas, Saran...","Department of Pediatric Endocrinology, Univers...",The increasing global prevalence of Autism Spe...
3,40934839,doi: 10.1016/j.seizure.2025.08.030,Tough to treat: What we know about managing PC...,Seizure,2025,"Aleksandra Tobiasz, Monika Hager, Julia Dębows...","Students' Scientific Society, Department of Pe...","PCDH19-related epilepsy is a rare, X-linked de..."
4,40934838,doi: 10.1016/j.seizure.2025.09.004,Characterizing CHD2-associated epilepsy: A mul...,Seizure,2025,"Anabel G Puri, Sean Woods, John M Schreiber, C...","Department of Pediatrics, Division of Pediatri...",CHD2 variants have been implicated in a spectr...
...,...,...,...,...,...,...,...,...
2995,40242676,pii: e80721,Current Clinical Practices for Gaming Disorder...,Cureus,2025,"Masaru Tateno, Yukie Tateno, Tomohiro Shirasak...","Pediatrics, Furuta Pediatric Clinic, Sapporo, ...",Gaming is a popular leisure activity among chi...
2996,40242361,pii: e102012,"Evaluating the feasibility, safety and efficac...",General psychiatry,2025,"Hangyu Tan, Mingyu Xu, Tai Ren, Lin Deng, Ling...",Ministry of Education - Shanghai Key Laborator...,NaN
2997,40242083,pii: 100765,Neuropsychiatric disorders in Chinese pediatri...,Epilepsy & behavior reports,2025,"Jie Fu, Qinrui Li, Genfu Zhang, Zhixian Yang, ...","Department of Pediatrics, Peking University Pe...",Tuberous sclerosis complex (TSC) is an autosom...
2998,40241535,pii: 24121,[The transition from child to adult health car...,Lakartidningen,2025,"Sven Bölte, Tatja Hirvikoski, Ulf Jonsson, Joh...",NaN,The transition from child to adult health care...
2999,40241368,doi: 10.7499/j.issn.1008-8830.2411142,[Advances in research on gender differences in...,Zhongguo dang dai er ke za zhi = Chinese journ...,2025,"Tong-Tong Jiang, Xiu-Qiong Li, Ting-Ting Zhao,...",NaN,Autism spectrum disorder (ASD) is a neurodevel...

# Embed data

## Preprocessing

In [4]:
# make all missing values empty strings
df = vectors.preprocess_for_vectorization(df).copy()

In [5]:
# combine text fields to be embedded
df_toembed = pd.DataFrame(df['journal']+' / '+df['title']+' / '+df['abstract'], columns=['text'])
df_toembed

                                                   text
0     Experimental neurology / Longitudinal analysis...
1     Journal of affective disorders / Adverse child...
2     Neuroscience / Endocrine circuitry in autism s...
3     Seizure / Tough to treat: What we know about m...
4     Seizure / Characterizing CHD2-associated epile...
...                                                 ...
2995  Cureus / Current Clinical Practices for Gaming...
2996  General psychiatry / Evaluating the feasibilit...
2997  Epilepsy & behavior reports / Neuropsychiatric...
2998  Lakartidningen / [The transition from child to...
2999  Zhongguo dang dai er ke za zhi = Chinese journ...

[3000 rows x 1 columns]

In [6]:
# how many words are the texts?
print(df_toembed['text'].apply(lambda x : \
len(x.split())).quantile([0.5, 0.75, 0.99, 1.0])) # percentiles

0.50    121.00
0.75    222.00
0.99    427.02
1.00    554.00
Name: text, dtype: float64

## Work, in batches

In [7]:
# vectorizer handle
print(vectors.model_handle)

multi-qa-MiniLM-L6-cos-v1

In [8]:
def batch_embed(batch):
    vectorizer = vectors.model # use locally saved model
    return {'embedding' : vectorizer.encode(batch['text'])}

In [9]:
# by batch, embed text
print(datetime.now())
dataset_to_embed = Dataset.from_pandas(df_toembed)
list_of_docs_with_embeddings = dataset_to_embed.map(batch_embed, batched=True, batch_size=32)
print(datetime.now())

2025-09-12 01:18:31.927453

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

2025-09-12 01:21:50.513556

In [10]:
# numpy format embeddings
embeddings = np.array([doc['embedding'] for doc in list_of_docs_with_embeddings])
embeddings

array([[-0.01331419,  0.03100735,  0.04415156, ...,  0.00295215,
         0.06678268, -0.03614511],
       [ 0.01364253, -0.00099124, -0.042556  , ...,  0.03705724,
        -0.04389741,  0.04818445],
       [-0.01475928, -0.06944643, -0.02060538, ...,  0.08121259,
         0.00358058,  0.06985687],
       ...,
       [-0.00197059, -0.02888306,  0.02024219, ...,  0.04638129,
         0.0319542 ,  0.04328557],
       [-0.02215269,  0.03331943, -0.05798261, ...,  0.04557109,
         0.06766746,  0.07463718],
       [-0.02466955,  0.01206873, -0.07816666, ...,  0.07700495,
         0.00649813,  0.05432483]], shape=(3000, 384))

# CSV file

In [11]:
# write CSV file
np.savetxt('../data/embed-kb.csv', embeddings, delimiter=',')

In [12]:
print(datetime.now())

2025-09-12 01:21:51.489017