In [1]:
import numpy as np
import pandas as pd
from datasets import Dataset
from datetime import datetime

In [2]:
import sys
sys.path.append('../scripts')
import vectors

# Load dataset

In [3]:
# load dataframe
df = pd.read_csv('../data/data-kb.csv', sep='\t', dtype=str) # they are all strings!
df

,pmid,elocationid,title,journal,year,author,affiliation,abstract
0,40939192,doi: 10.1097/WNF.0000000000000653,Psilocybin Use in the Autism Spectrum Disorder...,Clinical neuropharmacology,2025,"Jaime Moreno-Chaparro, Gabriela Castañeda-Mill...","Hospital Universitario Nacional de Colombia, B...",Due to the boom in the use of certain psychede...
1,40938792,doi: 10.1080/09638237.2025.2558503,Understanding the countermovement to online pr...,"Journal of mental health (Abingdon, England)",2025,"Vaughan Bell, Rhiannon White, Lucy Foulkes","Department of Experimental Psychology, Univers...",The self-presentation of psychiatric disorders...
2,40938690,doi: 10.1097/HRP.0000000000000437,"Comorbid Autism, Anxiety, and ADHD in a Preado...",Harvard review of psychiatry,2025,"Elizabeth Steuber, Jason Fogler, Oscar Bukstei...","From Harvard Medical School (Drs. Steuber, Fog...",Autism spectrum disorder (ASD) is often comorb...
3,40938348,doi: 10.1177/2161783X251378518,MazeOut Adaptive Serious Game: Evaluation of P...,Games for health journal,2025,"Alexandre Kira, Rodrigo G Pontes, Augusto K Pe...","School of Arts, Sciences and Humanities, Unive...",NaN
4,40938167,doi: 10.1080/00207578.2024.2394076,A reading of stereotypy in autism through the ...,The International journal of psycho-analysis,2025,Leandro Jofré,"Department of Clinical Psychology, Aix Marseil...",Stereotypies currently occupy an important pla...
...,...,...,...,...,...,...,...,...
2995,40246257,doi: 10.1016/j.neuroimage.2025.121217,Interbrain synchrony attenuation during a peer...,NeuroImage,2025,"I-Chun Chen, Hao-Che Hsu, Chia-Ling Chen, Meng...",Department of Physical Medicine and Rehabilita...,Young children with autism spectrum disorder (...
2996,40245451,doi: 10.1016/j.infbeh.2025.102057,Emerging sensitivity to talking mouth in infan...,Infant behavior & development,2025,"Masahiro Hata, Mingdi Xu, Yoko Hakuno, Eriko Y...","Center for Design of Future Symbiosis, Keio Un...",The talker's mouth provides significant multim...
2997,40245419,doi: 10.1097/AOG.0000000000005896,Acetaminophen in Pregnancy and Attention-Defic...,Obstetrics and gynecology,2025,Daniel W Cramer,"Department of Obstetrics, Gynecology and Repro...",NaN
2998,40245385,pii: e63378,Evaluating a Web-Based Application to Facilita...,JMIR research protocols,2025,"Eric Meyer, Hélène Sauzéon, Isabeau Saint-Supe...","Flowers team-project, Inria Research Center of...",An individual education plan (IEP) is a key el...
2999,40244830,doi: 10.1089/cap.2025.0021,NaN,Journal of child and adolescent psychopharmaco...,2025,"Sally Chu, H Yavuz Ince","Department of Psychiatry, Division of Child an...",NaN

# Embed data

## Preprocessing

In [4]:
# make all missing values empty strings
df = vectors.preprocess_for_vectorization(df).copy()

In [5]:
# combine text fields to be embedded
df_toembed = pd.DataFrame(df['journal']+' / '+df['title']+' / '+df['abstract'], columns=['text'])
df_toembed

                                                   text
0     Clinical neuropharmacology / Psilocybin Use in...
1     Journal of mental health (Abingdon, England) /...
2     Harvard review of psychiatry / Comorbid Autism...
3     Games for health journal / MazeOut Adaptive Se...
4     The International journal of psycho-analysis /...
...                                                 ...
2995  NeuroImage / Interbrain synchrony attenuation ...
2996  Infant behavior & development / Emerging sensi...
2997  Obstetrics and gynecology / Acetaminophen in P...
2998  JMIR research protocols / Evaluating a Web-Bas...
2999  Journal of child and adolescent psychopharmaco...

[3000 rows x 1 columns]

In [6]:
# how many words are the texts?
print(df_toembed['text'].apply(lambda x : \
len(x.split())).quantile([0.5, 0.75, 0.99, 1.0])) # percentiles

0.50    120.00
0.75    221.00
0.99    427.02
1.00    554.00
Name: text, dtype: float64

## Work, in batches

In [7]:
# vectorizer handle
print(vectors.model_handle)

multi-qa-MiniLM-L6-cos-v1

In [8]:
def batch_embed(batch):
    vectorizer = vectors.model # use locally saved model
    return {'embedding' : vectorizer.encode(batch['text'])}

In [9]:
# by batch, embed text
print(datetime.now())
dataset_to_embed = Dataset.from_pandas(df_toembed)
list_of_docs_with_embeddings = dataset_to_embed.map(batch_embed, batched=True, batch_size=32)
print(datetime.now())

2025-09-13 01:40:07.918161

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

2025-09-13 01:43:15.163391

In [10]:
# numpy format embeddings
embeddings = np.array([doc['embedding'] for doc in list_of_docs_with_embeddings])
embeddings

array([[-0.05128488, -0.07618695, -0.04385687, ...,  0.12556736,
        -0.03304618,  0.02123052],
       [-0.0085128 , -0.1184947 , -0.07520135, ...,  0.06691602,
        -0.02193654,  0.06407122],
       [ 0.00201873, -0.01339388, -0.03751471, ...,  0.08187042,
        -0.01049393,  0.08249757],
       ...,
       [-0.01568839, -0.05108237, -0.03650151, ...,  0.03155734,
         0.0297182 ,  0.08517637],
       [ 0.001147  ,  0.03333908, -0.0684872 , ..., -0.01114524,
         0.06441785,  0.0063974 ],
       [-0.0016648 , -0.0109417 , -0.09669736, ...,  0.05127326,
         0.12472019, -0.05116935]], shape=(3000, 384))

# CSV file

In [11]:
# write CSV file
np.savetxt('../data/embed-kb.csv', embeddings, delimiter=',')

In [12]:
print(datetime.now())

2025-09-13 01:43:16.092887