In [1]:
import pandas as pd
from datetime import datetime
from tqdm.auto import tqdm

# Import RAG

In [2]:
import sys
sys.path.append('../scripts')
import rag
import vectors
import ingest

# Loading data

## Answers to synthetic questions

In [3]:
df_synth_a = pd.read_csv('../data/data-synth-answer.csv', sep='\t', dtype=str)
df_synth_a

,pmid,ollama_seed,answer_llama3.2:1b,answer_gemma3:1b
0,40255413,0,Based on the context provided by the papers fr...,"Based on the provided text, the answer is:\n\n..."
1,40255413,1,Based on the provided context and papers from ...,"Okay, here’s an answer based on the provided t..."
2,40255413,2,Based on the context provided by the papers fr...,"Okay, based on the provided context and papers..."
3,40255413,3,"Based on the provided papers from PubMed, a co...","Okay, based on the provided context and papers..."
4,40255413,4,Based on the provided context and papers from ...,"Okay, let’s analyze the provided text and answ..."
5,40264093,0,Based on the context provided by the papers yo...,"Okay, here’s an analysis of the provided text,..."
6,40264093,1,Individuals on the autism spectrum can navigat...,"Okay, let’s answer your question based on the ..."
7,40264093,2,Based on the provided context and papers from ...,"Okay, based on the provided context and the in..."
8,40264093,3,Based on the context provided by the papers fr...,"Okay, here's an analysis of the provided text,..."
9,40264093,4,Individuals with Autism Spectrum Disorder (ASD...,"Okay, here's an analysis of the provided paper..."
10,40270009,0,Based on the context provided by the papers fr...,"Okay, let’s analyze the provided papers concer..."
11,40270009,1,Based on the provided context and PubMed paper...,"Okay, based on the provided context and the qu..."
12,40270009,2,Based on the context provided by the papers yo...,"Okay, let’s answer your question based on the ..."
13,40270009,3,Based on the provided context and papers from ...,"Okay, let’s tackle this question based on the ..."
14,40270009,4,Individuals on the autism spectrum may experie...,"Okay, based on the provided context and papers..."
15,40276113,0,Based on the provided context and papers from ...,"Okay, based on the provided context and papers..."
16,40276113,1,Based on the provided context and papers from ...,"Okay, let’s analyze the provided context and a..."
17,40276113,2,Based on the provided context of papers from P...,"Okay, let’s analyze the provided papers and ad..."
18,40276113,3,Based on the provided context and PubMed paper...,"Okay, let's tackle this question based on the ..."
19,40276113,4,Based on the provided context of papers from P...,"Okay, based on the provided context and papers..."
20,40287553,0,Based on the context provided by the set of pa...,"Okay, let’s tackle this question based on the ..."
21,40287553,1,Based on the provided context and papers from ...,"Okay, based on the provided text and the quest..."
22,40287553,2,Based on the provided context and papers from ...,"Okay, based on the provided context and papers..."
23,40287553,3,Individuals with Autism Spectrum Disorder (ASD...,"Okay, let’s answer your question based on the ..."
24,40287553,4,The impact of social interactions on cognitive...,"Okay, here's an answer to your question, drawi..."
25,40290839,0,One primary difference between the Feldenkrais...,"Okay, here's an analysis of the provided text,..."
26,40290839,1,Based on the provided context and papers from ...,"Okay, here's an answer based on the provided c..."
27,40290839,2,Based on the provided context and papers from ...,"Okay, let’s analyze the provided context and a..."
28,40290839,3,Based on the provided context and papers from ...,"Okay, based on the provided context and the qu..."
29,40290839,4,Based on the context provided by the papers fr...,"Okay, based on the provided papers and the con..."

## Synthetic questions

In [4]:
df_synth_q = pd.read_csv('../data/data-synth-question.csv', sep='\t', dtype=str)
df_synth_q

         pmid ollama_seed                                 synthetic_question
0    40255413           0  Is gastrointestinal (GI) problems more common ...
1    40255413           1  Does autism spectrum disorders affect a child'...
2    40255413           2  What is one possible underlying factor contrib...
3    40255413           3  What is a common challenge that many individua...
4    40255413           4  How do gastrointestinal (GI) symptoms affect t...
..        ...         ...                                                ...
495  40938164           0       Is autism a natural part of human diversity?
496  40938164           1  Can individuals with autism spectrum disorders...
497  40938164           2  What is it about individuals with autism spect...
498  40938164           3  What is the main difference between autism and...
499  40938164           4  Can autism be a contributing factor to suicida...

[500 rows x 3 columns]

## Abstracts

In [5]:
real_records = ingest.get_data_records('../data/data.csv')
df_abstr = pd.DataFrame.from_records(real_records)[['pmid', 'abstract']]
df_abstr

          pmid                                           abstract
0     40944767  Earlier identification of autistic traits is c...
1     40944766  This study examined friendship quality and the...
2     40944641  How do large-scale brain networks dynamically ...
3     40944186  Food selectivity is a prevalent and challengin...
4     40944170  Autism spectrum disorder (ASD) is a complex ne...
...        ...                                                ...
2995  40250148  To better understand medical comorbidity in pe...
2996  40249741  Vaccines have saved millions of lives, yet the...
2997  40249667  Genomic imprinting is an epigenetic phenomenon...
2998  40249409  Autistic children (AT) are known to exhibit di...
2999  40249163  The world's population is rapidly urbanising, ...

[3000 rows x 2 columns]

## Put together

In [6]:
df_together = df_synth_a.copy()
df_together = df_together.merge(df_synth_q, on=['pmid', 'ollama_seed'], how='left')
df_together = df_together.merge(df_abstr, on=['pmid'], how='left')
df_together

,pmid,ollama_seed,answer_llama3.2:1b,answer_gemma3:1b,synthetic_question,abstract
0,40255413,0,Based on the context provided by the papers fr...,"Based on the provided text, the answer is:\n\n...",Is gastrointestinal (GI) problems more common ...,Gastrointestinal (GI) symptoms are frequently ...
1,40255413,1,Based on the provided context and papers from ...,"Okay, here’s an answer based on the provided t...",Does autism spectrum disorders affect a child'...,Gastrointestinal (GI) symptoms are frequently ...
2,40255413,2,Based on the context provided by the papers fr...,"Okay, based on the provided context and papers...",What is one possible underlying factor contrib...,Gastrointestinal (GI) symptoms are frequently ...
3,40255413,3,"Based on the provided papers from PubMed, a co...","Okay, based on the provided context and papers...",What is a common challenge that many individua...,Gastrointestinal (GI) symptoms are frequently ...
4,40255413,4,Based on the provided context and papers from ...,"Okay, let’s analyze the provided text and answ...",How do gastrointestinal (GI) symptoms affect t...,Gastrointestinal (GI) symptoms are frequently ...
5,40264093,0,Based on the context provided by the papers yo...,"Okay, here’s an analysis of the provided text,...",Is there a link between autism and difficultie...,Autism Spectrum Disorder (ASD) affects social ...
6,40264093,1,Individuals on the autism spectrum can navigat...,"Okay, let’s answer your question based on the ...",How can individuals on the autism spectrum bes...,Autism Spectrum Disorder (ASD) affects social ...
7,40264093,2,Based on the provided context and papers from ...,"Okay, based on the provided context and the in...",Is Autism more likely to affect a person's abi...,Autism Spectrum Disorder (ASD) affects social ...
8,40264093,3,Based on the context provided by the papers fr...,"Okay, here's an analysis of the provided text,...",Is there a difference between the prevalence o...,Autism Spectrum Disorder (ASD) affects social ...
9,40264093,4,Individuals with Autism Spectrum Disorder (ASD...,"Okay, here's an analysis of the provided paper...",Can individuals with Autism Spectrum Disorder ...,Autism Spectrum Disorder (ASD) affects social ...
10,40270009,0,Based on the context provided by the papers fr...,"Okay, let’s analyze the provided papers concer...",What are some ways that researchers can better...,Although Ecological Momentary Assessment (EMA)...
11,40270009,1,Based on the provided context and PubMed paper...,"Okay, based on the provided context and the qu...",Can researchers use Real-time data from Ecolog...,Although Ecological Momentary Assessment (EMA)...
12,40270009,2,Based on the context provided by the papers yo...,"Okay, let’s answer your question based on the ...",What role does social interaction play in the ...,Although Ecological Momentary Assessment (EMA)...
13,40270009,3,Based on the provided context and papers from ...,"Okay, let’s tackle this question based on the ...",What are the key challenges in conducting Ecol...,Although Ecological Momentary Assessment (EMA)...
14,40270009,4,Individuals on the autism spectrum may experie...,"Okay, based on the provided context and papers...",How do some individuals on the autism spectrum...,Although Ecological Momentary Assessment (EMA)...
15,40276113,0,Based on the provided context and papers from ...,"Okay, based on the provided context and papers...",What role do social interactions play in the d...,"Artificial Intelligence (AI), has garnered att..."
16,40276113,1,Based on the provided context and papers from ...,"Okay, let’s analyze the provided context and a...",How is artificial intelligence impacting the d...,"Artificial Intelligence (AI), has garnered att..."
17,40276113,2,Based on the provided context of papers from P...,"Okay, let’s analyze the provided papers and ad...",What are the potential benefits and drawbacks ...,"Artificial Intelligence (AI), has garnered att..."
18,40276113,3,Based on the provided context and PubMed paper...,"Okay, let's tackle this question based on the ...",What role do artificial intelligence systems p...,"Artificial Intelligence (AI), has garnered att..."
19,40276113,4,Based on the provided context of papers from P...,"Okay, based on the provided context and papers...",Is artificial intelligence potentially used to...,"Artificial Intelligence (AI), has garnered att..."
20,40287553,0,Based on the context provided by the set of pa...,"Okay, let’s tackle this question based on the ...",What are the underlying neural mechanisms that...,Social interactions are essential for the surv...
21,40287553,1,Based on the provided context and papers from ...,"Okay, based on the provided text and the quest...",Is social interaction and behavior regulated b...,Social interactions are essential for the surv...
22,40287553,2,Based on the provided context and papers from ...,"Okay, based on the provided context and papers...",What are the key differences between individua...,Social interactions are essential for the surv...
23,40287553,3,Individuals with Autism Spectrum Disorder (ASD...,"Okay, let’s answer your question based on the ...",What are some common social behaviors that ind...,Social interactions are essential for the surv...
24,40287553,4,The impact of social interactions on cognitive...,"Okay, here's an answer to your question, drawi...",How do social interactions impact cognitive fu...,Social interactions are essential for the surv...
25,40290839,0,One primary difference between the Feldenkrais...,"Okay, here's an analysis of the provided text,...",What is one of the primary differences between...,This article presents the theoretical foundati...
26,40290839,1,Based on the provided context and papers from ...,"Okay, here's an answer based on the provided c...",Does movement therapy (such as Feldenkrais or ...,This article presents the theoretical foundati...
27,40290839,2,Based on the provided context and papers from ...,"Okay, let’s analyze the provided context and a...",What is unique about the way people with autis...,This article presents the theoretical foundati...
28,40290839,3,Based on the provided context and papers from ...,"Okay, based on the provided context and the qu...",What is the primary difference between the Fel...,This article presents the theoretical foundati...
29,40290839,4,Based on the context provided by the papers fr...,"Okay, based on the provided papers and the con...",How do autistic individuals often respond to s...,This article presents the theoretical foundati...

# Evaluation by cosine similarity

## Embed texts

In [7]:
# vectorizer handle
print(vectors.model_handle)

multi-qa-MiniLM-L6-cos-v1

In [8]:
# vector representations
print(datetime.now())
column_names_to_vectorize = ['answer_llama3.2:1b', 'answer_gemma3:1b', 'abstract']
vectorized = {name : vectors.model.encode(df_together[name].to_list()) \
for name in column_names_to_vectorize}
print(datetime.now())

2025-09-14 02:02:30.470221
2025-09-14 02:02:35.204101

## Compute cosine similarities

In [9]:
def get_cosine_similarities(model_handle):
    similarities = []
    for i in range(len(vectorized['abstract'])):
        vector_answer = vectorized['answer_'+model_handle][i]
        vector_abstract = vectorized['abstract'][i]
        similarity = vectors.model.similarity(vector_answer, vector_abstract).item()
        similarities.append(similarity)
    return similarities

In [10]:
# get similarities by model handle
df_similarities = pd.DataFrame({handle : get_cosine_similarities(handle) \
for handle in ['llama3.2:1b', 'gemma3:1b']})
df_similarities

    llama3.2:1b  gemma3:1b
0      0.825239   0.630141
1      0.500411   0.486283
2      0.920557   0.743348
3      0.354899   0.430685
4      0.842052   0.885504
5      0.567426   0.580948
6      0.604417   0.617429
7      0.774461   0.628251
8      0.812137   0.550834
9      0.763916   0.633520
10     0.643295   0.640594
11     0.828839   0.814063
12     0.380447   0.322418
13     0.691671   0.683454
14     0.603708   0.615276
15     0.372148   0.364975
16     0.878694   0.832655
17     0.810463   0.741464
18     0.847281   0.800072
19     0.876033   0.786069
20     0.711411   0.794847
21     0.631013   0.587696
22     0.479608   0.452713
23     0.606885   0.580515
24     0.587496   0.708215
25     0.674098   0.624849
26     0.634774   0.623812
27     0.368665   0.396846
28     0.695372   0.662674
29     0.277077   0.163506

## Compare models

In [11]:
# descriptive statistics, for llama3.2
df_similarities['llama3.2:1b'].describe()

count    30.000000
mean      0.652150
std       0.178849
min       0.277077
25%       0.572443
50%       0.658697
75%       0.811719
max       0.920557
Name: llama3.2:1b, dtype: float64

In [12]:
# descriptive statistics, for llama3.2
df_similarities['gemma3:1b'].describe()

count    30.000000
mean      0.612789
std       0.164969
min       0.163506
25%       0.558254
50%       0.626550
75%       0.733151
max       0.885504
Name: gemma3:1b, dtype: float64

In [13]:
# descriptive statistics, difference
(df_similarities['gemma3:1b']-df_similarities['llama3.2:1b']).describe()

count    30.000000
mean     -0.039361
std       0.083256
min      -0.261303
25%      -0.066257
50%      -0.026633
75%       0.008001
max       0.120719
dtype: float64

In [14]:
print(datetime.now())

2025-09-14 02:02:35.254281