In [1]:
import pandas as pd
from datetime import datetime
from tqdm.auto import tqdm

# Import RAG

In [2]:
import sys
sys.path.append('../scripts')
import rag
import vectors

# Loading data

## Answers to synthetic questions

In [3]:
df_synth_a = pd.read_csv('../data/data-synth-answer.csv', sep='\t', dtype=str)
df_synth_a

,pmid,ollama_seed,answer_llama3.2:1b,answer_gemma3:1b
0,40247149,0,Based on the provided context and papers from ...,"Okay, here's an answer based on the provided t..."
1,40247149,1,Based on the context provided by the papers fr...,"Okay, let’s tackle this question based on the ..."
2,40247149,2,Researchers believe that software tools play a...,"Okay, based on the provided context and papers..."
3,40247149,3,Based on the context provided by the papers yo...,"Okay, let’s analyze this context and answer yo..."
4,40247149,4,One potential limitation of using functional m...,"Okay, here’s an analysis of the provided text,..."
5,40266512,0,Based on the provided context and PubMed paper...,"Okay, based on the provided context and the pr..."
6,40266512,1,Based on the context provided by the papers fr...,"Okay, here's an analysis of the provided text,..."
7,40266512,2,Based on the provided context and papers from ...,"Okay, let’s analyze the provided papers concer..."
8,40266512,3,Based on the provided context and papers from ...,"Okay, here's an answer based on the provided c..."
9,40266512,4,Based on the context provided by the papers fr...,"Okay, let’s analyze the provided papers focusi..."
10,40287634,0,"Based on the provided context and papers, I ca...","Okay, let’s analyze the provided text and answ..."
11,40287634,1,Based on the context provided by the papers fr...,"Okay, based on the provided context and the qu..."
12,40287634,2,Based on the context provided by the papers fr...,"Okay, let’s analyze the provided text and answ..."
13,40287634,3,Based on the provided context of papers from P...,"Based on the provided text, the underlying cau..."
14,40287634,4,Based on the provided context and papers from ...,"Okay, let’s analyze the provided text and answ..."
15,40298931,0,Based on the provided context and papers from ...,"Okay, based on the provided context and papers..."
16,40298931,1,Based on the provided context and PubMed paper...,"Okay, here’s an answer based on the provided c..."
17,40298931,2,Based on the context provided by the papers fr...,"Okay, here's an answer based on the provided c..."
18,40298931,3,Based on the provided context and papers from ...,"Okay, based on the provided context and papers..."
19,40298931,4,Based on the provided context and papers from ...,"Okay, let’s analyze the provided papers based ..."
20,40302609,0,Based on the context provided by the papers fr...,"Okay, based on the provided context and papers..."
21,40302609,1,Based on the provided context of papers from P...,"Okay, let’s tackle this question based on the ..."
22,40302609,2,Based on the provided context and papers from ...,"Okay, here's an answer based on the provided c..."
23,40302609,3,"Based on the context provided, the role of imm...","Okay, let’s tackle this question based on the ..."
24,40302609,4,Based on the context provided by the set of pa...,"Okay, based on the provided context and papers..."
25,40306604,0,The main mechanism by which changes in the gut...,"Okay, let’s delve into the main mechanism by w..."
26,40306604,1,Based on the context provided by the set of pa...,"Okay, based on the provided papers, here’s an ..."
27,40306604,2,Based on the provided context of papers from P...,"Based on the provided text, here’s a breakdown..."
28,40306604,3,The current understanding of how changes in th...,"Okay, here's an analysis of the provided paper..."
29,40306604,4,Based on the provided context and papers from ...,"Okay, let's analyze the provided context and a..."

## Synthetic questions

In [4]:
df_synth_q = pd.read_csv('../data/data-synth-question.csv', sep='\t', dtype=str)
df_synth_q

         pmid ollama_seed                                 synthetic_question
0    40247149           0  What role do computer algorithms play in devel...
1    40247149           1  Is it more efficient to use machine learning a...
2    40247149           2  What role do researchers believe software tool...
3    40247149           3  What role do expert systems play in improving ...
4    40247149           4  What is one potential limitation of using fMRI...
..        ...         ...                                                ...
495  40933682           0  What is a major challenge that autistic studen...
496  40933682           1  Does a lack of visibility and understanding fr...
497  40933682           2  What drives college students with autism to de...
498  40933682           3  What is the primary reason that autistic colle...
499  40933682           4  Is there a specific aspect of autism that coll...

[500 rows x 3 columns]

## Abstracts

In [5]:
kb_records = rag.get_kb_records('../data/data-kb.csv')
df_abstr = pd.DataFrame.from_records(kb_records)[['pmid', 'abstract']]
df_abstr

          pmid                                           abstract
0     40938348
1     40938167  Stereotypies currently occupy an important pla...
2     40938164  The essay delineates a psychic phenomenon of i...
3     40938123      Here, we report the draft genome sequence of
4     40937558  Adolescence is a time of complex social and em...
...        ...                                                ...
2995  40245385  An individual education plan (IEP) is a key el...
2996  40244830
2997  40244560  Retinal ganglion cells (RGCs) are the only neu...
2998  40244507  The aim is to examine the relationship between...
2999  40244506  Previous studies have used cluster analysis to...

[3000 rows x 2 columns]

## Put together

In [6]:
df_together = df_synth_a.copy()
df_together = df_together.merge(df_synth_q, on=['pmid', 'ollama_seed'], how='left')
df_together = df_together.merge(df_abstr, on=['pmid'], how='left')
df_together

,pmid,ollama_seed,answer_llama3.2:1b,answer_gemma3:1b,synthetic_question,abstract
0,40247149,0,Based on the provided context and papers from ...,"Okay, here's an answer based on the provided t...",What role do computer algorithms play in devel...,Functional magnetic resonance imaging (fMRI) h...
1,40247149,1,Based on the context provided by the papers fr...,"Okay, let’s tackle this question based on the ...",Is it more efficient to use machine learning a...,Functional magnetic resonance imaging (fMRI) h...
2,40247149,2,Researchers believe that software tools play a...,"Okay, based on the provided context and papers...",What role do researchers believe software tool...,Functional magnetic resonance imaging (fMRI) h...
3,40247149,3,Based on the context provided by the papers yo...,"Okay, let’s analyze this context and answer yo...",What role do expert systems play in improving ...,Functional magnetic resonance imaging (fMRI) h...
4,40247149,4,One potential limitation of using functional m...,"Okay, here’s an analysis of the provided text,...",What is one potential limitation of using fMRI...,Functional magnetic resonance imaging (fMRI) h...
5,40266512,0,Based on the provided context and PubMed paper...,"Okay, based on the provided context and the pr...",What are the differences between the brain fun...,Cognitive dysmetria suggests a disorganization...
6,40266512,1,Based on the context provided by the papers fr...,"Okay, here's an analysis of the provided text,...",Here's a general question about autism that ca...,Cognitive dysmetria suggests a disorganization...
7,40266512,2,Based on the provided context and papers from ...,"Okay, let’s analyze the provided papers concer...",What are the key differences between autism sp...,Cognitive dysmetria suggests a disorganization...
8,40266512,3,Based on the provided context and papers from ...,"Okay, here's an answer based on the provided c...",What are some common characteristics or differ...,Cognitive dysmetria suggests a disorganization...
9,40266512,4,Based on the context provided by the papers fr...,"Okay, let’s analyze the provided papers focusi...",How do cognitive dysmetria and functional conn...,Cognitive dysmetria suggests a disorganization...
10,40287634,0,"Based on the provided context and papers, I ca...","Okay, let’s analyze the provided text and answ...",What is the main difference between Fragile X ...,Fragile X syndrome (FXS) is a neurodevelopment...
11,40287634,1,Based on the context provided by the papers fr...,"Okay, based on the provided context and the qu...",Is fragile X syndrome caused by DNA methylatio...,Fragile X syndrome (FXS) is a neurodevelopment...
12,40287634,2,Based on the context provided by the papers fr...,"Okay, let’s analyze the provided text and answ...",What triggers the abnormal methylation of the ...,Fragile X syndrome (FXS) is a neurodevelopment...
13,40287634,3,Based on the provided context of papers from P...,"Based on the provided text, the underlying cau...",What is the underlying cause of the difference...,Fragile X syndrome (FXS) is a neurodevelopment...
14,40287634,4,Based on the provided context and papers from ...,"Okay, let’s analyze the provided text and answ...",How does the body maintain normal gene express...,Fragile X syndrome (FXS) is a neurodevelopment...
15,40298931,0,Based on the provided context and papers from ...,"Okay, based on the provided context and papers...","What role, if any, does the gut microbiome pla...",Despite an increasing body of research showing...
16,40298931,1,Based on the provided context and PubMed paper...,"Okay, here’s an answer based on the provided c...",How effective is it to use probiotics or fecal...,Despite an increasing body of research showing...
17,40298931,2,Based on the context provided by the papers fr...,"Okay, here's an answer based on the provided c...","What role, if any, do the gut microbiota play ...",Despite an increasing body of research showing...
18,40298931,3,Based on the provided context and papers from ...,"Okay, based on the provided context and papers...",What role does the gut microbiome play in the ...,Despite an increasing body of research showing...
19,40298931,4,Based on the provided context and papers from ...,"Okay, let’s analyze the provided papers based ...",Is the link between gut microbiota and ASD a m...,Despite an increasing body of research showing...
20,40302609,0,Based on the context provided by the papers fr...,"Okay, based on the provided context and papers...",What role do immune cells play in the developm...,For 80 years there has been a link between aut...
21,40302609,1,Based on the provided context of papers from P...,"Okay, let’s tackle this question based on the ...",How do immune responses in individuals with au...,For 80 years there has been a link between aut...
22,40302609,2,Based on the provided context and papers from ...,"Okay, here's an answer based on the provided c...",What role does the immune system play in the d...,For 80 years there has been a link between aut...
23,40302609,3,"Based on the context provided, the role of imm...","Okay, let’s tackle this question based on the ...",What is the role of immune cells in regulating...,For 80 years there has been a link between aut...
24,40302609,4,Based on the context provided by the set of pa...,"Okay, based on the provided context and papers...",What is the role of immune cells in regulating...,For 80 years there has been a link between aut...
25,40306604,0,The main mechanism by which changes in the gut...,"Okay, let’s delve into the main mechanism by w...",What is the main mechanism by which changes in...,"The human gut microbiome, composed of a vast a..."
26,40306604,1,Based on the context provided by the set of pa...,"Okay, based on the provided papers, here’s an ...",Is autism caused by changes in the gut microbi...,"The human gut microbiome, composed of a vast a..."
27,40306604,2,Based on the provided context of papers from P...,"Based on the provided text, here’s a breakdown...",What is a key difference between individuals w...,"The human gut microbiome, composed of a vast a..."
28,40306604,3,The current understanding of how changes in th...,"Okay, here's an analysis of the provided paper...",What is the current understanding of how chang...,"The human gut microbiome, composed of a vast a..."
29,40306604,4,Based on the provided context and papers from ...,"Okay, let's analyze the provided context and a...",How does the gut microbiome influence brain de...,"The human gut microbiome, composed of a vast a..."

# Evaluation by cosine similarity

## Embed texts

In [7]:
# vectorizer handle
print(vectors.model_handle)

multi-qa-MiniLM-L6-cos-v1

In [8]:
# vector representations
print(datetime.now())
column_names_to_vectorize = ['answer_llama3.2:1b', 'answer_gemma3:1b', 'abstract']
vectorized = {name : vectors.model.encode(df_together[name].to_list()) \
for name in column_names_to_vectorize}
print(datetime.now())

2025-09-13 00:44:01.117272
2025-09-13 00:44:06.024778

## Compute cosine similarities

In [9]:
def get_cosine_similarities(model_handle):
    similarities = []
    for i in range(len(vectorized['abstract'])):
        vector_answer = vectorized['answer_'+model_handle][i]
        vector_abstract = vectorized['abstract'][i]
        similarity = vectors.model.similarity(vector_answer, vector_abstract).item()
        similarities.append(similarity)
    return similarities

In [10]:
# get similarities by model handle
df_similarities = pd.DataFrame({handle : get_cosine_similarities(handle) \
for handle in ['llama3.2:1b', 'gemma3:1b']})
df_similarities

    llama3.2:1b  gemma3:1b
0      0.616656   0.563908
1      0.594769   0.562691
2      0.679445   0.606250
3      0.446740   0.573610
4      0.785160   0.552165
5      0.479278   0.506215
6      0.185969   0.260058
7      0.550898   0.521722
8      0.477883   0.426746
9      0.811491   0.770920
10     0.632274   0.494103
11     0.915637   0.851179
12     0.806820   0.682993
13     0.730701   0.765948
14     0.667382   0.692193
15     0.737774   0.690017
16     0.647352   0.577804
17     0.768293   0.722726
18     0.715523   0.692529
19     0.757432   0.610867
20     0.770403   0.676262
21     0.764110   0.696457
22     0.712572   0.674826
23     0.710828   0.627158
24     0.646819   0.594125
25     0.695084   0.642308
26     0.697491   0.642144
27     0.218126   0.283394
28     0.705740   0.748631
29     0.798498   0.672860

## Compare models

In [11]:
# descriptive statistics, for llama3.2
df_similarities['llama3.2:1b'].describe()

count    30.000000
mean      0.657572
std       0.162292
min       0.185969
25%       0.620560
50%       0.701615
75%       0.762441
max       0.915637
Name: llama3.2:1b, dtype: float64

In [12]:
# descriptive statistics, for llama3.2
df_similarities['gemma3:1b'].describe()

count    30.000000
mean      0.612760
std       0.130359
min       0.260058
25%       0.562995
50%       0.634651
75%       0.691649
max       0.851179
Name: gemma3:1b, dtype: float64

In [13]:
# descriptive statistics, difference
(df_similarities['gemma3:1b']-df_similarities['llama3.2:1b']).describe()

count    30.000000
mean     -0.044811
std       0.073026
min      -0.232995
25%      -0.072283
50%      -0.051915
75%      -0.024539
max       0.126870
dtype: float64

In [14]:
print(datetime.now())

2025-09-13 00:44:06.074999